### ISSUE TITLE
Gradle Community Repository and Subsite

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#1]
We need a repository for random community stuff that does not need versioning along with Gradle releases and hence not a part of docs.gradle.org. I will build it as an open source MkDocs Multi-Repo site (with mainly Markdown), with listing for events, like GSoC contributor guidelines, and other content we have or want to add.

The website will be likely published as GitHub Pages or on community.gradle.org

## References

- Site: https://community.gradle.org/ 
- Contributing: https://community.gradle.org/CONTRIBUTING/

**Comment by martinbonnin** [comment]
I like MkDocs but out of curiosity, any reason to choose markdown when most Gradle docs are already AsciiDoc?

**Comment by oleg-nenashev** [comment]
@martinbonnin We do not choose Markdown only. We want to have support for Asciidoc, at least to some extent. We do not leverage complex Asciidoc features in docs.gradle.org, so the conversion is relatively straightforward.

On the other hand, we want to include existing repositories, and README.md and Markdown sub-sites (vanilla GitHub flavored Markdown, Jekyll & Co) are dominant across the Gradle ecosystem

**Comment by oleg-nenashev** [comment]
Basics are done, we will keep improving it incrementally
