### ISSUE TITLE
CFP - November Edition, Gradle Build Tool Newsletter

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#115]
We are assembling the next newsletter edition. As always, we want to include major updates from the community, including recent updates in Gradle Build Tool and plugins, new blogs and articles, and upcoming events. Any other big Gradle-related updates are welcome, too! See the [newsletter archive](https://newsletter.gradle.org/) for examples

If you want to suggest something, comment on this issue!

![image](https://github.com/gradle/community/assets/3000480/66f98019-fe1c-4af6-8ad2-2382bd9d68bf)

References:

- [Gradle Build Tool Newsletter archive](https://newsletter.gradle.org/)
- [Contributing to the newsletter](https://community.gradle.org/contributing/spread-the-word#newsletter)

P.S.: Bonus points for announcing the updates in `#community-news`on Slack and on [Gradle Forums](https://discuss.gradle.org/)!

**Comment by oleg-nenashev** [comment]
FTR, upcoming bigger items:

* Gradle 8.11 release and the patch releases. We should have a release video, too
  * https://docs.gradle.org/8.11/release-notes.html
  * https://github.com/gradle/gradle/issues?q=is%3Aissue%20state%3Aopen%20milestone%3A8.11.1 
* Declarative Gradle EAP2 release. Depends on https://github.com/gradle/declarative-gradle/pull/141 
* Hacktoberfest Summary

**Comment by cdsap** [comment]
Gradle 8.11: Faster Configuration Cache and Improved Configuration Time
https://dev.to/cdsap/gradle-811-faster-configuration-cache-and-improved-configuration-time-ja1

**Comment by oleg-nenashev** [comment]
It's live! https://newsletter.gradle.org/2024/11
Please submit new proposals in #124
