### ISSUE TITLE
CFP: April Newsletter

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#23]
We are assembling the newsletter for mid-March. As always, we want to include major updates from the community, including recent updates in Gradle Build Tool and plugins, new blogs and articles, and upcoming events. Any other big Gradle-related updates are welcome, too! See the [newsletter archive](https://newsletter.gradle.org/) for examples

If you want to suggest something, comment on this issue!

![image](https://github.com/gradle/community/assets/3000480/66f98019-fe1c-4af6-8ad2-2382bd9d68bf)

P.S.: Bonus points for announcing the updates in `#community-news`on Slack and on [Gradle Forums](https://discuss.gradle.org/)!

**Comment by StefMa** [comment]
I wrote a bit about non transitive r classes and compile avoidance:

https://stefma.medium.com/unveiling-the-reality-my-experiment-with-non-transitive-r-classes-and-compilation-avoidance-6296922db40f

**Comment by autonomousapps** [comment]
https://dev.to/autonomousapps/gradles-leaky-abstractions-declarativeish-shell-imperative-core-implementing-a-safeish-global-configuration-dsl-5e63

**Comment by autonomousapps** [comment]
Dependency Analysis Gradle Plugin v1.31.0 is now fully compliant with Isolated Projects (I think; hard to say when it's still experimental and a moving target). https://github.com/autonomousapps/dependency-analysis-gradle-plugin/blob/main/CHANGELOG.md#version-1310

**Comment by jjohannes** [comment]
New plugin release: [org.gradlex.jvm-dependency-conflict-resolution](https://gradlex.org/jvm-dependency-conflict-resolution/) 2.0

This redesigned plugin combines the functionality of the `org.gradlex.java-ecosystem-capabilities` and `dev.jacomet.logging-capabilities` plugins to ease dependency conflict detection and resolution in Java projects. It has a ton of improvements, including the new `jvmDependencyConflicts` DSL that lets you express resolution strategies and metadata patching for Java projects in a concise way.

**Comment by gabrielfeo** [comment]
New library release, 2024.1.0 of [develocity-api-kotlin](https://github.com/gabrielfeo/develocity-api-kotlin). It supports the latest release of Develocity from earlier this week (and the library is renamed to Develocity too).

**Comment by 2BAB** [comment]
New Book Release: [Extending Android Builds: Pragmatic Gradle and AGP Skills with Kotlin](https://www.amazon.com/gp/product/B0CZXPP2JS) by El Zhang

The book goes beyond Gradle configuration, it delves into the development of Gradle plugins that integrate with the Android Gradle Plugin (AGP) and other essential build tools, such as AAPT2, Kotlin Symbol Processing (KSP), and Bytecode manipulators.

After reading this book, you will be able to:

- Utilize the Kotlin language for both Gradle scripts and plugins.
- Author Gradle plugins/tasks with confidence while effectively interacting with AGP APIs and Gradle raw APIs.
- Monitor and modify various aspects of the Android build process, including resource files, source code, JVM bytecode, and even their combinations using AAPT2, Kotlin Symbol Processing (KSP), and multiple bytecode manipulators.
- Ensure that the plugin is both robust and low-cost to maintain, following the simple test pyramid.
- Adhere to the latest best practices in App architecture that align with many Gradle golden rules and offer extensibility for developers.
- Reduce the build time of the Android application and enhance the efficiency of their existing CI/CD workflows.

After years of quiet in the Gradle book market, this publication offers a fresh learning path for all Gradle and Android developers. It might be the first book to dissect the Android build system and its extending approaches, serving as the latest reference for anyone involved in Developer Productivity Engineering (DPE) on Android development.
