### ISSUE TITLE
CFP: May 2024 Newsletter 

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#27]
We are assembling the next newsletteredition. As always, we want to include major updates from the community, including recent updates in Gradle Build Tool and plugins, new blogs and articles, and upcoming events. Any other big Gradle-related updates are welcome, too! See the [newsletter archive](https://newsletter.gradle.org/) for examples

If you want to suggest something, comment on this issue!

![image](https://github.com/gradle/community/assets/3000480/66f98019-fe1c-4af6-8ad2-2382bd9d68bf)

P.S.: Bonus points for announcing the updates in `#community-news`on Slack and on [Gradle Forums](https://discuss.gradle.org/)!

**Comment by 2BAB** [comment]
Chapters 1~4 of the book '_Extending Android Builds_' are now open to everyone on the web. https://eab.2bab.com/

**Comment by 2BAB** [comment]
'Kotlin-oriented Gradle Essentials' (KOGE), a concise self-study handbook for Gradle. It lists a dozen confusing points for newcomers, points out the learning sequence, and links to appropriate reference materials - from questions, source code, and samples already available on the Internet. It's open-sourced and free. https://koge.2bab.com/#/

**Comment by liutikas** [comment]
An investigation of Gradle dependency signature verification of Guava that started using Gradle metadata for publishing
https://www.liutikas.net/2024/04/11/Where-Is-Your-Signature.html

**Comment by oleg-nenashev** [comment]
Thanks! Next month, I will make sure to publish my notes too.
There is quite a lot to mention in major and smaller updates :

- Welcome to GSoC contributors
- Gradle 8.8 release candidates
- KotlinConf and the Gradle Build Tool agenda there 
- First alpha releases of Declarative Gradle plugins, Declarative Gradle site launch with QuickStarts
- Gradle.org Website Updates
- New Gradle courses on https://dpeuniversity.gradle.com/app 

There are also many core updates in IDEs&Co from my twitter bookmarks

**Comment by oleg-nenashev** [comment]
Shipped!
