### ISSUE TITLE
CFP: June 2024 Newsletter - Gradle Build Tool and the ecosystem

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#34]
We are assembling the next newsletter edition. As always, we want to include major updates from the community, including recent updates in Gradle Build Tool and plugins, new blogs and articles, and upcoming events. Any other big Gradle-related updates are welcome, too! See the [newsletter archive](https://newsletter.gradle.org/) for examples

If you want to suggest something, comment on this issue!

![image](https://github.com/gradle/community/assets/3000480/66f98019-fe1c-4af6-8ad2-2382bd9d68bf)

References:

- [Gradle Build Tool Newsletter archive](https://newsletter.gradle.org/)
- [Contributing to the newsletter](https://community.gradle.org/contributing/spread-the-word#newsletter)

P.S.: Bonus points for announcing the updates in `#community-news`on Slack and on [Gradle Forums](https://discuss.gradle.org/)!

**Comment by jjohannes** [comment]
**Plugin Release**

Version `2.1.1` of the `org.gradlex.jvm-dependency-conflict-resolution` enables you to configure [global consistent resolution](https://gradlex.org/jvm-dependency-conflict-resolution/#consistent-resolution-block) for multi-project builds. With this feature, you ensure that the same versions of all dependencies are used across all classpaths of a multi-project Java build.

**Comment by oleg-nenashev** [comment]
Gradle Community site release: https://github.com/gradle/community/releases/tag/v1.0.0

**Comment by oleg-nenashev** [comment]
https://community.gradle.org/cookbook/

As a part of the Gradle documentation investment and the Gradle Community Hub effort, we have just released the [Gradle Cookbook](https://community.gradle.org/cookbook/) - an open-source collection of recipes, guides, and examples for the Gradle Build Tool. This is a complementary resource to the [Gradle User Manual](https://docs.gradle.org/current/userguide/userguide.html), which covers core capabilities maintained by the Gradle team.

The Gradle Cookbook is NOT a second-class citizen, but a new resource on the documentation engine and architecture. The goal of this portal is to offer solution-based documentation for end users about external integrations, including but not limited to CI/CD tools, IDEs, support for languages and frameworks, and various peripheral tools. If you have interesting use-case recipes to share, contributions are welcome! Check out the [contributor guide](https://community.gradle.org/cookbook/CONTRIBUTING/) for more info.
