### ISSUE TITLE
Call for Proposals: March newsletter

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#4]
We are assembling the newsletter for mid-March. As always, we want to include major updates from the community, including recent updates in the Gradle Build Tool and plugins, new blogs and articles, and upcoming events. Any other big Gradle-related updates are welcome, too! See the [newsletter archive](https://newsletter.gradle.org/) for examples

If you want to suggest something, comment on this issue!

![image](https://github.com/gradle/community/assets/3000480/66f98019-fe1c-4af6-8ad2-2382bd9d68bf)

P.S.: Bonus points for announcing the updates in `#community-news`on Slack and on [Gradle Forums](https://discuss.gradle.org/)!

**Comment by pioterj** [comment]
https://android-developers.googleblog.com/2024/02/android-studio-iguana-is-stable.html

**Comment by jjohannes** [comment]
> The latest release of the GradleX [Extra Java Module Info](https://github.com/gradlex-org/extra-java-module-info) plugin now supports automatically generating complete `module-info.class` files for libraries that do not yet provide one. The content of the `module-info.class` is computed from the libraries metadata. New versions of the GradleX [Java Module Dependencies](https://github.com/gradlex-org/java-module-dependencies) and  [Java Module Testing](https://github.com/gradlex-org/java-module-testing) plugins are also available.

**Comment by mrhaki** [comment]
Three blog posts: 
* [Gradle Goodness: Using Environment Variables Lazily](https://blog.mrhaki.com/2024/02/gradle-goodness-using-environment.html)](https://blog.mrhaki.com/2024/02/gradle-goodness-using-environment.html)
* [Gradle Goodness: Using System Properties Lazily](https://blog.mrhaki.com/2024/02/gradle-goodness-using-system-properties.html)](https://blog.mrhaki.com/2024/02/gradle-goodness-using-system-properties.html)
* [Gradle Goodness: Organizing Tasks Using The Task Container](https://blog.mrhaki.com/2024/03/gradle-goodnesss-organizing-tasks-using.html)](https://blog.mrhaki.com/2024/03/gradle-goodnesss-organizing-tasks-using.html)

**Comment by oleg-nenashev** [comment]
Items from my list:

* Gratatoille
* What's new in the Gradle community?
* Intellij Platform Gradle Plugin 2.0 EAP
* Declarative Gradle updates

**Comment by oleg-nenashev** [comment]
It is published now: https://newsletter.gradle.org/2024/03
