### ISSUE TITLE
CFP: July Newsletter

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#48]
We are assembling the next newsletter edition. As always, we want to include major updates from the community, including recent updates in Gradle Build Tool and plugins, new blogs and articles, and upcoming events. Any other big Gradle-related updates are welcome, too! See the [newsletter archive](https://newsletter.gradle.org/) for examples

If you want to suggest something, comment on this issue!

![image](https://github.com/gradle/community/assets/3000480/66f98019-fe1c-4af6-8ad2-2382bd9d68bf)

References:

- [Gradle Build Tool Newsletter archive](https://newsletter.gradle.org/)
- [Contributing to the newsletter](https://community.gradle.org/contributing/spread-the-word#newsletter)

P.S.: Bonus points for announcing the updates in `#community-news`on Slack and on [Gradle Forums](https://discuss.gradle.org/)!

**Comment by oleg-nenashev** [comment]
If we could expand on Unber and Gradle: Uber Becomes Kotlin™ Foundation Silver Member and invests in integrations for Kotlin in Gradle and other build systems - https://www.uber.com/en-CH/blog/kotlin-foundation-member/

**Comment by pioterj** [comment]
https://blog.jetbrains.com/idea/2024/06/intellij-idea-2024-2-eap-6/#improved-experience-with-gradle-build-scripts
