### ISSUE TITLE
CFP: August newsletter

### ISSUE THREAD

**Issue by pioterj** [gradle/community#52]

**Comment by pioterj** [comment]
https://medium.com/@janbarari/supercharge-your-builds-with-the-gradle-analytics-plugin-20db70d7f311

**Comment by oleg-nenashev** [comment]
* Shadow plugin is now a part of GradleUp
* GradleUp got a new site: https://gradleup.com/

**Comment by pioterj** [comment]
https://blog.jetbrains.com/platform/2024/07/intellij-platform-gradle-plugin-2-0/

**Comment by pioterj** [comment]
https://www.droidcon.com/2024/07/17/ultimate-iteration-speeds-with-gradle-configuration-cache/

**Comment by erichaagdev** [comment]
https://spring.io/blog/2024/08/15/a-bootiful-podcast-gradle-and-develocity-engineer-and-spring-community

**Comment by jjohannes** [comment]
**New Release (Plugin)**

Java Module Dependencies Plugin v1.7 adds functionality to configure the location of subprojects with Java Modules in the _settings.gradle_ file. With this, Java projects can define dependencies exclusively in _module-info.java_ files and do not require _build.gradle_ files anymore. [Read More](https://github.com/gradlex-org/java-module-dependencies/tree/main?tab=readme-ov-file#project-structure-definition-when-using-this-plugin-as-settings-plugin).

**Comment by oleg-nenashev** [comment]
It is sent out. I will try to publish the archive today
