### ISSUE TITLE
CFP: Gradle Newsletter - September Edition

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#62]
We are assembling the next newsletter edition. As always, we want to include major updates from the community, including recent updates in Gradle Build Tool and plugins, new blogs and articles, and upcoming events. Any other big Gradle-related updates are welcome, too! See the [newsletter archive](https://newsletter.gradle.org/) for examples

If you want to suggest something, comment on this issue!

![image](https://github.com/gradle/community/assets/3000480/66f98019-fe1c-4af6-8ad2-2382bd9d68bf)

References:

- [Gradle Build Tool Newsletter archive](https://newsletter.gradle.org/)
- [Contributing to the newsletter](https://community.gradle.org/contributing/spread-the-word#newsletter)

P.S.: Bonus points for announcing the updates in `#community-news`on Slack and on [Gradle Forums](https://discuss.gradle.org/)!

**Comment by oleg-nenashev** [comment]
Kotlin 0.20.0 and support for Gradle 8.6+ in tool chain https://kotlinlang.slack.com/archives/C0922A726/p1724344853184389?thread_ts=1724344853.184389&cid=C0922A726

**Comment by cdsap** [comment]
Resource observability case study: jemalloc in Android builds https://dev.to/cdsap/resource-observability-case-study-jemalloc-in-android-builds-22og

**Comment by oleg-nenashev** [comment]
Also https://github.com/quarkusio/quarkus/pull/42496 , credits to @cdsap 🎉

**Comment by gabrielfeo** [comment]
[Develocity API Kotlin 2024.2.0](https://github.com/gabrielfeo/develocity-api-kotlin/releases/tag/2024.2.0) was released, supporting Develocity API 2024.2

**Comment by britter** [comment]
New plugin from the GradleX team: https://github.com/gradlex-org/reproducible-builds

This plugin applies reproducibility settings to some of Gradle's built-in tasks.

**Comment by cdsap** [comment]
Metaspace in JVM Builds:
https://www.jasonpearson.dev/metaspace-in-jvm-builds/ by @kaeawc

**Comment by oleg-nenashev** [comment]
@britter @cdsap - Sorry for not updating the issue on time. The CFPs was closed on Friday. I will try to include the items

**Comment by oleg-nenashev** [comment]
Shipped: https://newsletter.gradle.org/2024/09
