### ISSUE TITLE
CFP: Gradle Build Tool - October Newsletter

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#77]
We are assembling the next newsletter edition. As always, we want to include major updates from the community, including recent updates in Gradle Build Tool and plugins, new blogs and articles, and upcoming events. Any other big Gradle-related updates are welcome, too! See the [newsletter archive](https://newsletter.gradle.org/) for examples

If you want to suggest something, comment on this issue!

![image](https://github.com/gradle/community/assets/3000480/66f98019-fe1c-4af6-8ad2-2382bd9d68bf)

References:

- [Gradle Build Tool Newsletter archive](https://newsletter.gradle.org/)
- [Contributing to the newsletter](https://community.gradle.org/contributing/spread-the-word#newsletter)

P.S.: Bonus points for announcing the updates in `#community-news`on Slack and on [Gradle Forums](https://discuss.gradle.org/)!

**Comment by oleg-nenashev** [comment]
Nice things on Gradle and VS Code:

- https://devblogs.microsoft.com/java/java-on-visual-studio-code-update-august-2024/ 
- GSoC video by @Tanish-Ranjan

**Comment by autonomousapps** [comment]
This isn't really about Gradle, but it's relevant to Gradle Kotlin developers (and productivity!)

https://dev.to/autonomousapps/acab-fire-the-code-style-cop-in-your-head-m8b

**Comment by oleg-nenashev** [comment]
Of course, we need a custom Halloween image in the ending :pumpkin:

**Comment by cdsap** [comment]
* Kotlin JVM args: Inheritance & Defaults (from the Gradle daemon) by @kaeawc: https://www.jasonpearson.dev/kotlin-jvm-args-inheritance-and-defaults/ 
* Telltale: Automating Experimentation in Gradle Builds: https://dev.to/cdsap/telltale-automating-experimentation-in-gradle-builds-1h9m

**Comment by autonomousapps** [comment]
and another https://dev.to/autonomousapps/one-click-dependencies-fix-191p

**Comment by KengoTODA** [comment]
Our blog post describing how we halved pre-merge build time by Develocity 🤝 
https://dev.henry.jp/entry/dpe-journey

**Comment by oleg-nenashev** [comment]
Thanks everyone! The October edition is live https://newsletter.gradle.org/2024/10
