### ISSUE TITLE
Links should be darker in light mode

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#83]
Currently, the links are too light. I suggest making headers darker, and using the header color for links instead

* Header Color: #19274f (`--gradle-blue-darker:`)
* Links Color: 1b3262

![Screenshot 2024-09-30 at 18 47 23](https://github.com/user-attachments/assets/8b7d9427-120a-44b4-8e4e-89f4d2e4da54)

**Comment by ivonasto** [comment]
What do you think? 

Header Color: #19274f (--gradle-blue-darker) 
Links Color: #209BC4 (--gradle-blue) (taken from header)

![image](https://github.com/user-attachments/assets/497c837c-24f0-42a3-8295-dffe03cd5854)

Links Color: #1b3262 (suggested)

![image](https://github.com/user-attachments/assets/2f4b0f41-ec5a-469d-a636-eac48c66ab5e)

**Comment by oleg-nenashev** [comment]
The first option looks better.

I don't have opinion about header colors. docs.gradle.org used black/white headers, so indeed we can follow a similar style by having headers in light mode of the same color as the header/footer background

**Comment by oleg-nenashev** [comment]
Thanks for the patch @ivonasto ! It looks much better now. Hopefully you had a good experience with the tooling for this site :)

**Comment by ivonasto** [comment]
It was great, thank you for creating first-time issues :)

**Comment by oleg-nenashev** [comment]
Thanks for feedback!
