### ISSUE TITLE
Add previews to the Community Website

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#93]
We're doing previews for the gradle.org website with GitHub Actions (private at the moment), and there is no reason to not do the same with the open source repositories like community.gradle.org. It would help to review the bigger patches

Location: https://github.com/gradle/community-site-preview

**Comment by ivonasto** [comment]
Hi @oleg-nenashev, can I give it a try?

**Comment by oleg-nenashev** [comment]
@ivonasto this ticket requires access to the GitHub organization administration, so I do not think it is easy to do if you are not a Gradle employee. TBH I would recommend taking another ticket.

**Comment by ivonasto** [comment]
All right, thank you
