### ISSUE TITLE
List the key channels on the Slack channels page

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/community#96]
https://community.gradle.org/contributing/community-slack/ is missing the list of the suggested channels. I suggest putting a list of the most popular channels (Community News, Community Support, etc.) with some initial descriptions. Later, the same descriptions will be added to Slack Canvas.

P.S: Arguably, it is me who should have done it already, but I am underwater. Any help would be appreciated!

**Comment by pragyananda** [comment]
i want to work on that .

**Comment by oleg-nenashev** [comment]
It is fixed now.
@pragyananda please do not hesitate to create pull requests right away. We normally do not assign issues small issues.
